import { ApplyColorScheme } from './lib/color_scheme';
import { InitDefaultSettings } from './lib/init_default_settings';
import { SaveSettings } from './lib/settings_storage';
import { ApplyTheme } from './lib/theme';
import { Settings } from './types/settings_interface';

let settings: Settings;

const getErrorMessage = (error: unknown): string => {
    return error instanceof Error ? error.message : String(error);
};

const initPopup = async () => {
    ApplyColorScheme(settings.color_scheme);
    ApplyTheme(settings.theme);

    const popup_url = new URL(window.location.href);
    const feed_urls = JSON.parse(popup_url.searchParams.get('feedlinks') ?? '[]') as string[];
    const feed_list = document.getElementById('feed_url_list') as HTMLTableElement;
    const settings_button = document.getElementById('settings_button') as HTMLButtonElement;
    const exclude_site_button = document.getElementById('exclude_site_button') as HTMLButtonElement;
    const popup_status = document.getElementById('popup_status') as HTMLElement;

    settings_button.addEventListener('click', () => {
        chrome.runtime.openOptionsPage();
    });

    exclude_site_button.addEventListener('click', async () => {
        try {
            const current_tab = await chrome.tabs.query({ active: true, currentWindow: true });
            const tab = current_tab[0];
            if (!tab?.url || typeof tab.id !== 'number') throw new Error('The active tab cannot be ignored.');
            const new_entry: Settings['ignored_sites'][number] = {
                pattern: new URL(tab.url).hostname,
                match_type: 'subdomain',
            };
            const current_settings = await InitDefaultSettings();
            if (!current_settings.ignored_sites.some((site) => site.pattern === new_entry.pattern)) {
                await SaveSettings({
                    ...current_settings,
                    ignored_sites: [...current_settings.ignored_sites, new_entry],
                });
            }
            chrome.runtime.sendMessage({ type: 'exclude_site', tabId: tab.id });
            window.close();
        } catch (error: unknown) {
            popup_status.textContent = getErrorMessage(error);
            popup_status.title = popup_status.textContent;
        }
    });

    for (let feed_url of feed_urls) {
        const tr = document.createElement('tr');
        const td1 = document.createElement('td');
        const td2 = document.createElement('td');
        const td3 = document.createElement('td');
        const a = document.createElement('a');
        const info_div = document.createElement('span');
        const copy_btn = document.createElement('button');

        if (feed_url.startsWith('__template__:')) {
            info_div.setAttribute('class', 'help-icon');
            info_div.setAttribute('role', 'note');
            info_div.setAttribute('aria-label', 'This candidate was generated by a Feed Template');
            info_div.innerText = '!';
            feed_url = feed_url.slice('__template__:'.length);
        } else if (feed_url.startsWith('_')) {
            info_div.setAttribute('class', 'help-icon');
            info_div.setAttribute('role', 'note');
            info_div.setAttribute('aria-label', 'This candidate was found by Extended Feed Scan');
            info_div.innerText = '!';
            feed_url = feed_url.slice(1);
        }

        td1.setAttribute('class', 'col1 feed_url');
        td2.setAttribute('class', 'col2');
        td3.setAttribute('class', 'col3 copy_button_area');
        a.setAttribute('target', '_blank');
        a.setAttribute('rel', 'noreferrer');
        a.setAttribute('href', feed_url);
        a.setAttribute('title', feed_url);
        a.innerText = feed_url;
        copy_btn.setAttribute('class', 'copy_button');
        copy_btn.type = 'button';
        copy_btn.setAttribute('aria-live', 'polite');
        copy_btn.setAttribute('aria-label', `Copy ${feed_url} to clipboard`);
        copy_btn.setAttribute('title', 'Copy to clipboard');
        copy_btn.setAttribute('value', feed_url);
        copy_btn.innerText = 'Copy';

        td1.appendChild(a);
        if (info_div.innerText) {
            info_div.tabIndex = 0;
            td2.appendChild(info_div);
            td2.appendChild(document.createTextNode('\u00A0'));
        }
        td3.appendChild(copy_btn);
        tr.appendChild(td1);
        tr.appendChild(td2);
        tr.appendChild(td3);
        feed_list.appendChild(tr);
    }

    const copy_buttons = document.querySelectorAll('.copy_button');
    for (const button of Array.from(copy_buttons)) {
        button.addEventListener('click', async (event) => {
            const feed_url = (event.target as HTMLButtonElement).value;
            const copy_button = button as HTMLButtonElement;
            try {
                await navigator.clipboard.writeText(feed_url);
                copy_button.innerText = 'Copied!';
                copy_button.title = 'Copied to clipboard';
                copy_button.setAttribute('aria-label', `Copied ${feed_url} to clipboard`);
            } catch {
                copy_button.innerText = 'Copy failed';
                copy_button.title = 'Could not copy to clipboard';
                copy_button.setAttribute('aria-label', `Could not copy ${feed_url}`);
            }
            setTimeout(() => {
                copy_button.innerText = 'Copy';
                copy_button.title = 'Copy to clipboard';
                copy_button.setAttribute('aria-label', `Copy ${feed_url} to clipboard`);
            }, 2000);
        });
    }
};

(async () => {
    settings = await InitDefaultSettings();
    if (document.readyState === 'interactive' || document.readyState === 'complete') {
        initPopup();
    } else {
        document.addEventListener('DOMContentLoaded', initPopup, { once: true });
    }
})();
